### PR TITLE
[WIP] Add centralized logging chart

### PR DESCRIPTION
**Pull request by alexbrand**
Add a new chart for setting up a centralized logging solution based on elasticsearch, fluentd, and kibana.

To do:
- [x] Use configmap for fluentd
- [x] Clean up default fluentd configmap
- [x] Expose fluentd configmap in values.yaml
- [ ] Create a kibana container that does not use x-pack
      Using community maintained one for testing.. will maintain our own
- [ ] Create elasticsearch container that does not use x-pack
      Using community maintained one for testing.. will maintain our own
- [ ] Use debian-based fluentd daemonset to be able to use systemd plugin
      to get kubelet logs
- [ ] Use configmap for elasticsearch?
- [ ] Elasticsearch resource requests/limits
- [ ] Anti-affinity?
- [x] Persitent Volume
- [x] Stateful set?
- [ ] Curator CronJob
- [ ] Documentation

### CODE REVIEW

**Comment by alexbrand** [comment]
Actually, I need to convert the elasticsearch-data deployment into a stateful set.

**Comment by dkoshkin** [comment]
A few comments:
- [ ]  Rename the chart to either `efk` or `logging` - needs further discussion
- [ ] IMO running `helm install kismatic/efk` should create a fully functional cluster(although probably not something that should be run in production)
  - This means: using `NodePorts` instead of relying on Ingress or LB or `ClusterIP`
  - Use `emptyDir` by default

**Comment by alexbrand** [comment]
Thanks! I knew I was missing a couple of things. Will work on these soon.

**Comment by swade1987** [comment]
@dkoshkin @alexbrand you guys happy for me to delete the branch?

**Pull request merged**
