### PR TITLE
Add prometheus-grafana chart

### PR DESCRIPTION
**Pull request by dkoshkin**
- Create a parent chart that depends on prometheus and grafana charts
- Update Grafana chart to latest upstream version
- Remove Prometheus chart in favor of the upstream one
- Modify the Makefile script to automatically build charts with dependencies
- Dockerized build

### CODE REVIEW

**Comment by alexbrand** [comment]
Does helm support includes in the values file? Having that > 1k lines config in there is a bit painful. Not sure if anyone will actually touch that. Wondering if there is a way to have that config in a separate file.

**Comment by dkoshkin** [comment]
Unfortunately there is no way to include multiple files. More in the [README].(https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/values_files.md)

**Comment by swade1987** [comment]
Remove all "latest" tags from the chart.

**Comment by swade1987** [comment]
After using the joint chart with clients I see it as more of a hindrance than useful. Please see some reasons below:

1. It adds additional complexity and makes extending the chart very cumbersome as you need to add `global` values that can we used within both charts.

2. The charts become very coupled, they are utilities that can have their own release cadence. Additionally, I can use Prometheus without Grafana and also may want to use Grafana for more than just Prometheus metrics. 

3. It makes the values chart very difficult to manage as it's over 3000 lines, I know we have a PR already submitted to resolve some of this.

**Additional Gotchas:**

- The resource values for `kube-state-metrics` in the default Prometheus chart aren't accurate when I uncommented them the service stopped working.

**Comment by willvrny** [comment]
I'd agree with @swade1987 observations. I would avoid the joint chart as it adds coupling without much benefit. The user can always install either charts separately. 

It comes down to whether you want to have a separate chart for Prometheus and Grafana specifically for Kismatic. Do you think it might diverge from the main charts based on Kismatic requirements?

**Comment by swade1987** [comment]
@willvrny these should be "apprenda best-practice" charts which are useful to our range of clients. An example of this is that I feel all resources deployed onto a Kubernetes cluster should have resource limits by default. The community charts have these commented out and when you uncomment them they add issues.

**Comment by dkoshkin** [comment]
Merging for now and going to improve with more PRs

**Comment by swade1987** [comment]
@dkoshkin @alexbrand you guys happy for me to delete the branch?

**Pull request merged**
